## Methodology

Prescribing estimates are based on a sophisticated methodology which includes linking primary care prescription address data to care home addresses in [AddressBase Plus](https://www.ordnancesurvey.co.uk/business-government/products/addressbase) and [CQC data](https://anypoint.mulesoft.com/exchange/portals/care-quality-commission-5/4d36bd23-127d-4acf-8903-ba292ea615d4/cqc-syndication-1/). The address matching method has been made available as an R package named [addressMatchR](https://github.com/nhsbsa-data-analytics/addressMatchR). The methodology is also available [online](https://rpubs.com/nhsbsa-data-analytics/methodology). Throughout the project the NHSBSA ensured data was protected and secure and adhered to the Caldicott guardian principles.

This analysis addresses a key gap in knowledge and gives valuable insights which can inform the use and management of medicines in care homes to help improve health outcomes, quality of care and ensure value. __It should however be noted that data from the 2020/21 financial year was at the height of the COVID-19 pandemic and data from the 2021/22 financial year was toward the end of the pandemic.__ Prescribing patterns may change in subsequent years.

Patient count estimates are of care home residents aged 65 years and over __receiving prescriptions__. A care home resident that received no prescriptions would not appear in this data, meaning care home patient count estimates will be lower than the monthly actual care home population. These monthly estimates will be higher than 2021 Census estimates which are based on occupancy on Census day.

The methodology is described in full on a [blog post on RPubs](https://rpubs.com/nhsbsa-data-analytics/methodology).